spring:
  #sql:
    #init:
      #mode: always
  #datasource:
    #initialization-mode: always
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.json
    #default-schema: DATABROKER
---
spring:
  profiles: default
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
#                type: trace

---
spring:
  profiles: cloud
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect